name: squidly1408
description: A Portfolio about Lucas Newman.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  video_player: ^2.5.1
  gantt_chart: ^0.3.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.8.4
  firebase_database: ^10.2.5
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  holding_gesture: ^1.2.0
  go_router: ^11.1.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    #logo
    - lib/assets/images/logo.svg
    - lib/assets/images/logo_heart.svg

    #homepage banners
    - lib/assets/images/homepage/homepage_banner.png
    - lib/assets/images/homepage/about_me_bannner.png
    - lib/assets/images/homepage/projects_banner.png
    - lib/assets/images/homepage/outlearning_banner.png
    - lib/assets/images/homepage/skills_banner.png

    #project pages banner
    - lib/assets/images/projects/project_banner.png
    - lib/assets/images/projects/mentors_banner.png
    - lib/assets/images/projects/resources_banner.png
    - lib/assets/images/projects/skills_banner.png

    #other projects banners
    - lib/assets/images/other_projects/projects_banner.png
    - lib/assets/images/other_projects/left_middle.png
    - lib/assets/images/other_projects/right_middle.png
    - lib/assets/images/other_projects/left_bottom.png
    - lib/assets/images/other_projects/right_bottom.png

    #skills
    - lib/assets/images/skills/1.png
    - lib/assets/images/skills/2.png
    - lib/assets/images/skills/3.png
    - lib/assets/images/skills/4.png
    - lib/assets/images/skills/5.png
    - lib/assets/images/skills/6.png
    - lib/assets/images/skills/7.png
    - lib/assets/images/skills/8.png
    - lib/assets/images/skills/9.png
    - lib/assets/images/skills/10.png
    - lib/assets/images/skills/11.png
    - lib/assets/images/skills/12.png

    #project 1 skills
    - lib/assets/images/project1/1.png
    - lib/assets/images/project1/2.png
    - lib/assets/images/project1/3.png
    - lib/assets/images/project1/4.png
    - lib/assets/images/project1/5.png
    - lib/assets/images/project1/6.png
    - lib/assets/images/project1/7.png
    - lib/assets/images/project1/8.png
    - lib/assets/images/project1/9.png

    #project 2 skills
    - lib/assets/images/project2/1.png
    - lib/assets/images/project2/2.png
    - lib/assets/images/project2/3.png
    - lib/assets/images/project2/4.png
    - lib/assets/images/project2/5.png

    #project 3 skills
    - lib/assets/images/project3/1.png
    - lib/assets/images/project3/2.png
    - lib/assets/images/project3/3.png

    #replacement image
    - lib/assets/images/replacement_image.png

    #outlearning images
    - lib/assets/images/outlearning/outlearning_banner.png
    - lib/assets/images/outlearning/divider.png
    - lib/assets/images/outlearning/saphi.png
    - lib/assets/images/outlearning/uon.png
    - lib/assets/images/outlearning/clickk.png
    - lib/assets/images/outlearning/nubots.png
    - lib/assets/images/outlearning/footer_image.png
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: lib/assets/fonts/SourceCodePro-Medium.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
